#!/bin/bash

# https://www.youtube.com/watch?v=YinR8zIK_3g&list=PLgYy5YCbiYbHh1ST5__ffj99eAjVfAwgy&index=5
# 


echo "ssh demo"
echo "1: whereis ssh"
whereis ssh
echo "2: which ssh "
which ssh

echo  "ssh://[user@]hostname[:port]"
ssh bandit4@bandit.labs.overthewire.org -p 2220
# password = pIwrPrtPN36QITSp3EQaw936yaFoFgAB
# whoami -> bandit4
# exit


