#!/bin/bash

# https://www.youtube.com/watch?v=YinR8zIK_3g&list=PLgYy5YCbiYbHh1ST5__ffj99eAjVfAwgy&index=5
#


echo "ssh demo"
echo "1: whereis ssh"
whereis ssh
echo "2: which ssh "
which ssh

echo "ssh://[user@]hostname[:port]"
ssh bandit4@bandit.labs.overthewire.org -p 2220
# password = pIwrPrtPN36QITSp3EQaw936yaFoFgAB
# whoami -> bandit4
# exit


When ssh used with -i option will use a file with a private key to use for login.
We will use our sshkey.private file. We now know our full command to type to
remote into bandit14 user.

ssh -i ./sshkey.private bandit14@localhost
-i says use a specified privatekey file, ./sshkey.private is our key location,
a
After we enter this command we will be asked: Are you sure you want to
continue connecting (yes/no)?
Type yes
We are now connected to bandit14
